'------------------------------------------------------------------------------------------
' SymbolsData.bas version 1.03
' #include once "SymbolsData.bas"
'------------------------------------------------------------------------------------------
FreeBASIC_Symbols:
Data 472		' symbol count
data "__date__", "__date_iso__", "__fb_64bit__", "__fb_argc__", "__fb_argv__"
data "__fb_arm__", "__fb_asm__", "__fb_backend__", "__fb_bigendian__", "__fb_build_date__"
data "__fb_cygwin__", "__fb_darwin__", "__fb_debug__", "__fb_dos__", "__fb_err__"
data "__fb_fpmode__", "__fb_fpu__", "__fb_freebsd__", "__fb_gcc__", "__fb_lang__"
data "__fb_linux__", "__fb_main__", "__fb_min_version__", "__fb_mt__", "__fb_netbsd__"
data "__fb_openbsd__", "__fb_option_byval__", "__fb_option_dynamic__", "__fb_option_escape__", "__fb_option_explicit__"
data "__fb_option_gosub__", "__fb_option_private__", "__fb_out_dll__", "__fb_out_exe__", "__fb_out_lib__"
data "__fb_out_obj__", "__fb_pcos__", "__fb_signature__", "__fb_sse__", "__fb_unix__"
data "__fb_vectorize__", "__fb_ver_major__", "__fb_ver_minor__", "__fb_ver_patch__", "__fb_version__"
data "__fb_win32__", "__fb_xbox__", "__file__", "__file_nq__", "__function__"
data "__function_nq__", "__line__", "__path__", "__time__", "#assert"
data "#define", "#else", "#elseif", "#endif", "#endmacro"
data "#error", "#if", "#ifdef", "#ifndef", "#inclib"
data "#include", "#lang", "#libpath", "#line", "#macro"
data "#pragma", "#print", "#undef", "$dynamic", "$include"
data "$lang", "$static", "abs", "abstract", "access"
data "acos", "add", "alias", "allocate", "alpha"
data "and", "andalso", "and", "any", "append"
data "as", "asc", "asin", "asm", "assert"
data "assertwarn", "atan2", "atn", "base"
data "beep", "bin", "binary", "bit", "bitreset"
data "bitset", "bload", "boolean", "bsave", "byref"
data "byte", "byval", "call"
data "callocate", "case", "cast", "cbool", "cbyte"
data "cdbl", "cdecl", "chain", "chdir", "chr"
data "cint", "circle", "class", "clear", "clng"
data "clngint", "close", "cls", "color", "command"
data "common", "condbroadcast", "condcreate", "conddestroy", "condsignal"
data "condwait", "const", "constructor"
data "continue", "cos", "cptr", "cshort"
data "csign", "csng", "csrlin", "cubyte", "cuint"
data "culng", "culngint", "cunsg", "curdir", "cushort"
data "custom", "cvd", "cvi", "cvl", "cvlongint"
data "cvs", "cvshort", "data", "date", "dateadd"
data "datediff", "datepart", "dateserial", "datevalue", "day"
data "deallocate", "declare", "defbyte", "defdbl", "defined"
data "defint", "deflng", "deflongint", "defshort", "defsng"
data "defstr", "defubyte", "defuint", "defulongint", "defushort"
data "delete", "destructor", "dim", "dir"
data "do", "double", "draw"
data "dylibfree", "dylibload", "dylibsymbol", "else", "elseif"
data "encoding", "end", "enum"
data "environ", "eof", "eqv", "erase"
data "erfn", "erl", "ermn", "err", "error"
data "event", "exec", "exepath", "exit", "exp"
data "export", "extends", "extern", "false"
data "field", "fileattr", "filecopy", "filedatetime", "fileexists"
data "filelen", "fix", "flip", "for"
data "format", "frac", "fre", "freefile"
data "function", "get", "getjoystick", "getkey"
data "getmouse", "gosub", "goto", "hex", "hibyte"
data "hiword", "hour", "if", "iif", "imageconvertrow"
data "imagecreate", "imagedestroy", "imageinfo", "imp", "implements"
data "import", "inkey", "inp", "input"
data "instr", "instrrev", "int"
data "integer", "is", "isdate", "isredirected"
data "kill", "lbound", "lcase", "left", "len"
data "let", "lib", "line"
data "lobyte", "loc", "local", "locate", "lock"
data "lof", "log", "long", "longint", "loop"
data "loword", "lpos", "lprint", "lset", "ltrim"
data "mid", "minute", "mkd", "mkdir"
data "mki", "mkl", "mklongint", "mks", "mkshort"
data "mod", "month", "monthname", "multikey", "mutexcreate"
data "mutexdestroy", "mutexlock", "mutexunlock", "naked", "name"
data "namespace", "new", "next"
data "not", "now", "object", "oct", "offsetof"
data "on", "once", "open"
data "operator", "option", "or"
data "orelse", "out", "output", "overload", "override"
data "paint", "palette", "pascal", "pcopy", "peek"
data "pmap", "point", "pointcoord", "pointer", "poke"
data "pos", "preserve", "preset"
data "print", "private"
data "procptr", "property", "protected:", "pset"
data "ptr", "public", "public:", "put"
data "random", "randomize", "read"
data "reallocate", "redim", "rem", "reset", "restore"
data "resume", "return", "rgb", "rgba"
data "right", "rmdir", "rnd", "rset", "rtrim"
data "run", "sadd", "scope", "screen"
data "screencopy", "screencontrol", "screenevent", "screenglproc", "screeninfo"
data "screenlist", "screenlock", "screenptr", "screenres", "screenset"
data "screensync", "screenunlock", "second", "seek"
data "select", "setdate", "setenviron", "setmouse", "settime"
data "sgn", "shared", "shell", "shl", "short"
data "shr", "sin", "single", "sizeof", "sleep"
data "space", "spc", "sqr", "static"
data "stdcall", "step", "stick", "stop", "str"
data "strig", "string", "strptr"
data "sub", "swap", "system", "tab", "tan"
data "then", "this", "threadcall", "threadcreate", "threaddetach"
data "threadwait", "time", "timer", "timeserial", "timevalue"
data "to", "trans", "trim", "true", "type"
data "typeof", "ubound", "ubyte"
data "ucase", "uinteger", "ulong", "ulongint", "union"
data "unlock", "unsigned", "until", "ushort", "using"
data "va_arg", "va_first", "va_next", "val"
data "vallng", "valint", "valuint", "valulng", "var"
data "varptr", "view", "virtual", "wait"
data "wbin", "wchr", "weekday", "weekdayname", "wend"
data "while", "whex", "width", "window"
data "windowtitle", "winput", "with", "woct"
data "write", "wspace", "wstr", "wstring"
data "xor", "year", "zstring"
